//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sztek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.lobby = new HashSet<lobby>();
            this.results = new HashSet<results>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public byte[] password { get; set; }
        public int game_id { get; set; }
        public bool in_lobby { get; set; }
        public string country { get; set; }
        public string description { get; set; }
    
        public virtual games games { get; set; }
        public virtual ICollection<lobby> lobby { get; set; }
        public virtual ICollection<results> results { get; set; }
    }
}
