//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sztek.SztekWebServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.30.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gameserver/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gameserver/", ConfigurationName="SztekWebServiceReference.Main")]
    public interface Main {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gameserver/Main/startGameServerRequest", ReplyAction="http://gameserver/Main/startGameServerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sztek.SztekWebServiceReference.IOException), Action="http://gameserver/Main/startGameServer/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sztek.SztekWebServiceReference.startGameServerResponse startGameServer(Sztek.SztekWebServiceReference.startGameServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameserver/Main/startGameServerRequest", ReplyAction="http://gameserver/Main/startGameServerResponse")]
        System.Threading.Tasks.Task<Sztek.SztekWebServiceReference.startGameServerResponse> startGameServerAsync(Sztek.SztekWebServiceReference.startGameServerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startGameServer", WrapperNamespace="http://gameserver/", IsWrapped=true)]
    public partial class startGameServerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gameserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serverPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gameserver/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ip1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gameserver/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ip2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gameserver/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ip3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gameserver/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ip4;
        
        public startGameServerRequest() {
        }
        
        public startGameServerRequest(string serverPort, string ip1, string ip2, string ip3, string ip4) {
            this.serverPort = serverPort;
            this.ip1 = ip1;
            this.ip2 = ip2;
            this.ip3 = ip3;
            this.ip4 = ip4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startGameServerResponse", WrapperNamespace="http://gameserver/", IsWrapped=true)]
    public partial class startGameServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gameserver/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public startGameServerResponse() {
        }
        
        public startGameServerResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainChannel : Sztek.SztekWebServiceReference.Main, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainClient : System.ServiceModel.ClientBase<Sztek.SztekWebServiceReference.Main>, Sztek.SztekWebServiceReference.Main {
        
        public MainClient() {
        }
        
        public MainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sztek.SztekWebServiceReference.startGameServerResponse Sztek.SztekWebServiceReference.Main.startGameServer(Sztek.SztekWebServiceReference.startGameServerRequest request) {
            return base.Channel.startGameServer(request);
        }
        
        public string startGameServer(string serverPort, string ip1, string ip2, string ip3, string ip4) {
            Sztek.SztekWebServiceReference.startGameServerRequest inValue = new Sztek.SztekWebServiceReference.startGameServerRequest();
            inValue.serverPort = serverPort;
            inValue.ip1 = ip1;
            inValue.ip2 = ip2;
            inValue.ip3 = ip3;
            inValue.ip4 = ip4;
            Sztek.SztekWebServiceReference.startGameServerResponse retVal = ((Sztek.SztekWebServiceReference.Main)(this)).startGameServer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sztek.SztekWebServiceReference.startGameServerResponse> Sztek.SztekWebServiceReference.Main.startGameServerAsync(Sztek.SztekWebServiceReference.startGameServerRequest request) {
            return base.Channel.startGameServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sztek.SztekWebServiceReference.startGameServerResponse> startGameServerAsync(string serverPort, string ip1, string ip2, string ip3, string ip4) {
            Sztek.SztekWebServiceReference.startGameServerRequest inValue = new Sztek.SztekWebServiceReference.startGameServerRequest();
            inValue.serverPort = serverPort;
            inValue.ip1 = ip1;
            inValue.ip2 = ip2;
            inValue.ip3 = ip3;
            inValue.ip4 = ip4;
            return ((Sztek.SztekWebServiceReference.Main)(this)).startGameServerAsync(inValue);
        }
    }
}
