//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sztek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class games
    {
        public games()
        {
            this.results = new HashSet<results>();
        }
    
        public int game_id { get; set; }
        public bool status { get; set; }
        public string game_name { get; set; }
        public int max_player { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<results> results { get; set; }
    }
}
