//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sztek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lobby
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public bool status { get; set; }
    
        public virtual users users { get; set; }
    }
}
